# Default configuration for the PDF question_and_answer Tool
chunk_size: 1200 # Number of characters per text chunk
chunk_overlap: 200 # Overlap between adjacent chunks
top_k_papers: 5 # Number of papers to rank and retrieve
top_k_chunks: 25 # Number of chunks to retrieve
reranker:
  model: "nvidia/nv-rerankqa-mistral-4b-v3"
  api_key: ${oc.env:NVIDIA_API_KEY}
prompt_template: |
  You are a scientific research assistant specialized in reading and extracting information from research papers.
  Your role is to answer questions by retrieving relevant information from the provided context.

  - Provide detailed, structured, and well-argued explanations—not just brief summaries.
  - Cite specific sources using onky the title of the paper.
  - If the context is insufficient, clearly state that more information is needed.

  Context:
  {context}

  Question: {question}

  Your answer should be comprehensive, accurate, and clearly structured for a scientific audience.
